site_name: Know
site_url: https://KAFKA2306.github.io/know/
repo_url: https://github.com/KAFKA2306/know
repo_name: KAFKA2306/know

site_description: Multi-Knowledge Base for Life, Dev, and more.
site_author: KAFKA2306
copyright: Copyright &copy; 2026 KAFKA2306

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KAFKA2306

validation:
  links:
    absolute_links: warn
    anchors: warn

theme:
  name: material
  language: ja
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Noto Sans JP
    code: Roboto Mono

plugins:
  - search:
      lang: 
        - en
        - ja
  - tags

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - nl2br
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Bookmarks:
      - Top: bookmarks/index.md
      - Dev:
          - Top: bookmarks/Dev/index.md
          - AI: bookmarks/Dev/AI/index.md
          - Data: bookmarks/Dev/Data/index.md
          - Tool: bookmarks/Dev/Tool/index.md
      - Game:
          - Top: bookmarks/Game/index.md
          - VR: bookmarks/Game/VR/index.md
          - Board: bookmarks/Game/Board/index.md
          - Digital: bookmarks/Game/Digital/index.md
      - Finance:
          - Top: bookmarks/Finance/index.md
          - Bank: bookmarks/Finance/Bank/index.md
          - Market: bookmarks/Finance/Market/index.md
          - Crypto: bookmarks/Finance/Crypto/index.md
      - Service:
          - Top: bookmarks/Service/index.md
          - Cloud: bookmarks/Service/Cloud/index.md
          - Social: bookmarks/Service/Social/index.md
      - Media:
          - Top: bookmarks/Media/index.md
          - Video: bookmarks/Media/Video/index.md
          - Music: bookmarks/Media/Music/index.md
      - Academic:
          - Top: bookmarks/Academic/index.md
          - Library: bookmarks/Academic/Library/index.md
          - Research: bookmarks/Academic/Research/index.md
      - Life:
          - Top: bookmarks/Life/index.md
          - Shopping: bookmarks/Life/Shopping/index.md
          - Utility: bookmarks/Life/Utility/index.md
      - Other: bookmarks/Other/index.md
  - Life:
      - Tax: life/tax/index.md
      - Money: life/money/credit-card-investment-2026.md
  - Dev:
      - Agent: dev/agent/index.md
      - WSL: dev/wsl/index.md
