site_name: Know
theme:
  name: material
  language: ja
nav:
  - Home: index.md
  - Bookmarks:
      - Top: bookmarks/index.md
      - AI: bookmarks/AI/index.md
      - Academic: bookmarks/Academic/index.md
      - Dev: bookmarks/Dev/index.md
      - Finance: bookmarks/Finance/index.md
      - Game: bookmarks/Game/index.md
      - Life: bookmarks/Life/index.md
      - Media: bookmarks/Media/index.md
