[project]
name = "know"
version = "0.1.0"
description = "Multi-Knowledge Base"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.5.49",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
